workflows:
  ios-project-debug: # workflow ID
    name: iOS debug # workflow name
    environment:
      xcode: 15.0.1
      vars:
          XCODE_PROJECT: "GameLibrary/GameLibrary.xcodeproj"
          XCODE_SCHEME: "GameLibrary"
    scripts:
      - name: Clean derived data
        script: |
          rm -rf $HOME/Library/Developer/Xcode/DerivedData
      - name: Resolve SPM dependencies
        script: |
          xcodebuild -resolvePackageDependencies -project "$XCODE_PROJECT" -scheme "$XCODE_SCHEME"
      - name: Run tests
        script: |
          xcodebuild \
          -project "$XCODE_PROJECT" \
          -scheme "$XCODE_SCHEME" \
          -sdk iphonesimulator \
          -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.0.1' \
          clean build test CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
      - name: Build debug app
        script: |
          set -o pipefail && \
          xcodebuild build \
          -project "$XCODE_PROJECT" \
          -scheme "$XCODE_SCHEME" \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO \
          -verbose | xcpretty
    artifacts:
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
    publishing:
      email:
        recipients:
          - yudha.pieters@gmail.com
