workflows:
  ios-project-debug:
    name: iOS debug
    environment:
      xcode: latest
      cocoapods: default
      vars:
          XCODE_PROJECT: "GameLibrary/GameLibrary.xcodeproj"
          XCODE_WORKSPACE : "GameLibrary/GameLibrary.xcworkspace"
          XCODE_SCHEME: "GameLibrary"
    scripts:
      - name: Clean derived data
        script: |
          rm -rf $HOME/Library/Developer/Xcode/DerivedData
      - name: Run tests
        script: |
          xcodebuild \
          -project "$XCODE_PROJECT" \
          -scheme "$XCODE_SCHEME" \
          -sdk iphonesimulator \
          -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.0' \
          clean build test \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          -verbose
      - name: Build debug app
        script: |
          xcodebuild build \
          -project "$XCODE_PROJECT" \
          -scheme "$XCODE_SCHEME" \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO \
          -verbose
    artifacts:
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
    publishing:
      email:
        recipients:
          - yudha.pieters@gmail.com
